// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -destination=./mock/service_mock.go
//

// Package mock_participant is a generated GoMock package.
package mock_participant

import (
	context "context"
	reflect "reflect"

	domain "github.com/brunodmartins/church-members-api/internal/constants/domain"
	participant "github.com/brunodmartins/church-members-api/internal/modules/participant"
	wrapper "github.com/brunodmartins/church-members-api/platform/aws/wrapper"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateParticipant mocks base method.
func (m *MockService) CreateParticipant(ctx context.Context, arg1 *domain.Participant) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateParticipant", ctx, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateParticipant indicates an expected call of CreateParticipant.
func (mr *MockServiceMockRecorder) CreateParticipant(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateParticipant", reflect.TypeOf((*MockService)(nil).CreateParticipant), ctx, arg1)
}

// DeleteParticipant mocks base method.
func (m *MockService) DeleteParticipant(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteParticipant", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteParticipant indicates an expected call of DeleteParticipant.
func (mr *MockServiceMockRecorder) DeleteParticipant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteParticipant", reflect.TypeOf((*MockService)(nil).DeleteParticipant), ctx, id)
}

// GetParticipant mocks base method.
func (m *MockService) GetParticipant(ctx context.Context, id string) (*domain.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParticipant", ctx, id)
	ret0, _ := ret[0].(*domain.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipant indicates an expected call of GetParticipant.
func (mr *MockServiceMockRecorder) GetParticipant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipant", reflect.TypeOf((*MockService)(nil).GetParticipant), ctx, id)
}

// SearchParticipant mocks base method.
func (m *MockService) SearchParticipant(ctx context.Context, querySpecification wrapper.QuerySpecification, postSpecification ...participant.Specification) ([]*domain.Participant, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, querySpecification}
	for _, a := range postSpecification {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchParticipant", varargs...)
	ret0, _ := ret[0].([]*domain.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchParticipant indicates an expected call of SearchParticipant.
func (mr *MockServiceMockRecorder) SearchParticipant(ctx, querySpecification any, postSpecification ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, querySpecification}, postSpecification...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchParticipant", reflect.TypeOf((*MockService)(nil).SearchParticipant), varargs...)
}

// UpdateParticipant mocks base method.
func (m *MockService) UpdateParticipant(ctx context.Context, arg1 *domain.Participant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateParticipant", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateParticipant indicates an expected call of UpdateParticipant.
func (mr *MockServiceMockRecorder) UpdateParticipant(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateParticipant", reflect.TypeOf((*MockService)(nil).UpdateParticipant), ctx, arg1)
}
