coverage:
  status:
    patch: no
ignore:
  - "platform"
  - "cmd"
  - "internal/handler/graphql/graph_config.go"
  - "internal/handler/graphql/graph_fields.go"
  - "internal/handler/graphql/member_resolver.go"
  - "main.go"