FROM golang:1.13

WORKDIR /go/src/app
COPY . .

RUN go get -d -v ./... && go install -v ./... && go build

ENV VPR_CHURCH_MEMBERS_DATABASE_URL $VPR_CHURCH_MEMBERS_DATABASE_URL \
    VPR_CHURCH_MEMBERS_ACCESS_TOKEN $VPR_CHURCH_MEMBERS_ACCESS_TOKEN \
    SCOPE $SCOPE \
    VPR_CHURCH_NAME $VPR_CHURCH_NAME \
    APP_LANG $APP_LANG

CMD ["church-members-api"]