FROM golang:1.13

WORKDIR /go/src/app
COPY . .

RUN go get -d -v ./...
RUN go install -v ./...
RUN go build

ENV VPR_CHURCH_MEMBERS_DATABASE_URL $VPR_CHURCH_MEMBERS_DATABASE_URL
ENV VPR_CHURCH_MEMBERS_ACCESS_TOKEN $VPR_CHURCH_MEMBERS_ACCESS_TOKEN
ENV SCOPE $SCOPE

CMD ["church-members-api"]