// Code generated by MockGen. DO NOT EDIT.
// Source: ./reportsService.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockReportsGenerator is a mock of ReportsGenerator interface.
type MockReportsGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockReportsGeneratorMockRecorder
}

// MockReportsGeneratorMockRecorder is the mock recorder for MockReportsGenerator.
type MockReportsGeneratorMockRecorder struct {
	mock *MockReportsGenerator
}

// NewMockReportsGenerator creates a new mock instance.
func NewMockReportsGenerator(ctrl *gomock.Controller) *MockReportsGenerator {
	mock := &MockReportsGenerator{ctrl: ctrl}
	mock.recorder = &MockReportsGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportsGenerator) EXPECT() *MockReportsGeneratorMockRecorder {
	return m.recorder
}

// BirthdayReport mocks base method.
func (m *MockReportsGenerator) BirthdayReport() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BirthdayReport")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BirthdayReport indicates an expected call of BirthdayReport.
func (mr *MockReportsGeneratorMockRecorder) BirthdayReport() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BirthdayReport", reflect.TypeOf((*MockReportsGenerator)(nil).BirthdayReport))
}

// ClassificationReport mocks base method.
func (m *MockReportsGenerator) ClassificationReport(classification string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClassificationReport", classification)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClassificationReport indicates an expected call of ClassificationReport.
func (mr *MockReportsGeneratorMockRecorder) ClassificationReport(classification interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClassificationReport", reflect.TypeOf((*MockReportsGenerator)(nil).ClassificationReport), classification)
}

// LegalReport mocks base method.
func (m *MockReportsGenerator) LegalReport() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LegalReport")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LegalReport indicates an expected call of LegalReport.
func (mr *MockReportsGeneratorMockRecorder) LegalReport() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LegalReport", reflect.TypeOf((*MockReportsGenerator)(nil).LegalReport))
}

// MarriageReport mocks base method.
func (m *MockReportsGenerator) MarriageReport() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarriageReport")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarriageReport indicates an expected call of MarriageReport.
func (mr *MockReportsGeneratorMockRecorder) MarriageReport() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarriageReport", reflect.TypeOf((*MockReportsGenerator)(nil).MarriageReport))
}

// MemberReport mocks base method.
func (m *MockReportsGenerator) MemberReport() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MemberReport")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MemberReport indicates an expected call of MemberReport.
func (mr *MockReportsGeneratorMockRecorder) MemberReport() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MemberReport", reflect.TypeOf((*MockReportsGenerator)(nil).MemberReport))
}
