// Code generated by MockGen. DO NOT EDIT.
// Source: ./auth_service.go
//
// Generated by this command:
//
//	mockgen -source=./auth_service.go -destination=./mock/auth_service_mock.go
//

// Package mock_security is a generated GoMock package.
package mock_security

import (
	context "context"
	reflect "reflect"

	domain "github.com/brunodmartins/church-members-api/internal/constants/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ConfirmEmail mocks base method.
func (m *MockService) ConfirmEmail(ctx context.Context, userName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmEmail", ctx, userName)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmEmail indicates an expected call of ConfirmEmail.
func (mr *MockServiceMockRecorder) ConfirmEmail(ctx, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmEmail", reflect.TypeOf((*MockService)(nil).ConfirmEmail), ctx, userName)
}

// GenerateToken mocks base method.
func (m *MockService) GenerateToken(church *domain.Church, username, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", church, username, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockServiceMockRecorder) GenerateToken(church, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockService)(nil).GenerateToken), church, username, password)
}

// GetRoles mocks base method.
func (m *MockService) GetRoles(ctx context.Context, token string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoles", ctx, token)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoles indicates an expected call of GetRoles.
func (mr *MockServiceMockRecorder) GetRoles(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoles", reflect.TypeOf((*MockService)(nil).GetRoles), ctx, token)
}

// IdentifyChurch mocks base method.
func (m *MockService) IdentifyChurch(ctx context.Context, churchAbbreviation, churchID string) (*domain.Church, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IdentifyChurch", ctx, churchAbbreviation, churchID)
	ret0, _ := ret[0].(*domain.Church)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentifyChurch indicates an expected call of IdentifyChurch.
func (mr *MockServiceMockRecorder) IdentifyChurch(ctx, churchAbbreviation, churchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentifyChurch", reflect.TypeOf((*MockService)(nil).IdentifyChurch), ctx, churchAbbreviation, churchID)
}

// SendConfirmEmail mocks base method.
func (m *MockService) SendConfirmEmail(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendConfirmEmail", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendConfirmEmail indicates an expected call of SendConfirmEmail.
func (mr *MockServiceMockRecorder) SendConfirmEmail(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendConfirmEmail", reflect.TypeOf((*MockService)(nil).SendConfirmEmail), ctx, user)
}
