// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -destination=./mock/service_mock.go
//

// Package mock_member is a generated GoMock package.
package mock_member

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/brunodmartins/church-members-api/internal/constants/domain"
	member "github.com/brunodmartins/church-members-api/internal/modules/member"
	wrapper "github.com/brunodmartins/church-members-api/platform/aws/wrapper"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetMember mocks base method.
func (m *MockService) GetMember(ctx context.Context, id string) (*domain.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMember", ctx, id)
	ret0, _ := ret[0].(*domain.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMember indicates an expected call of GetMember.
func (mr *MockServiceMockRecorder) GetMember(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMember", reflect.TypeOf((*MockService)(nil).GetMember), ctx, id)
}

// RetireMembership mocks base method.
func (m *MockService) RetireMembership(ctx context.Context, id, reason string, date time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetireMembership", ctx, id, reason, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetireMembership indicates an expected call of RetireMembership.
func (mr *MockServiceMockRecorder) RetireMembership(ctx, id, reason, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetireMembership", reflect.TypeOf((*MockService)(nil).RetireMembership), ctx, id, reason, date)
}

// SaveMember mocks base method.
func (m *MockService) SaveMember(ctx context.Context, member *domain.Member) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMember", ctx, member)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMember indicates an expected call of SaveMember.
func (mr *MockServiceMockRecorder) SaveMember(ctx, member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMember", reflect.TypeOf((*MockService)(nil).SaveMember), ctx, member)
}

// SearchMembers mocks base method.
func (m *MockService) SearchMembers(ctx context.Context, querySpecification wrapper.QuerySpecification, postSpecification ...member.Specification) ([]*domain.Member, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, querySpecification}
	for _, a := range postSpecification {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchMembers", varargs...)
	ret0, _ := ret[0].([]*domain.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMembers indicates an expected call of SearchMembers.
func (mr *MockServiceMockRecorder) SearchMembers(ctx, querySpecification any, postSpecification ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, querySpecification}, postSpecification...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMembers", reflect.TypeOf((*MockService)(nil).SearchMembers), varargs...)
}

// UpdateContact mocks base method.
func (m *MockService) UpdateContact(ctx context.Context, memberID string, contact domain.Contact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContact", ctx, memberID, contact)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateContact indicates an expected call of UpdateContact.
func (mr *MockServiceMockRecorder) UpdateContact(ctx, memberID, contact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContact", reflect.TypeOf((*MockService)(nil).UpdateContact), ctx, memberID, contact)
}
