// Code generated by MockGen. DO NOT EDIT.
// Source: ./reportsService.go
//
// Generated by this command:
//
//	mockgen -source=./reportsService.go -destination=./mock/reports_mock.go
//

// Package mock_report is a generated GoMock package.
package mock_report

import (
	context "context"
	reflect "reflect"

	reportType "github.com/brunodmartins/church-members-api/internal/constants/enum/reportType"
	report "github.com/brunodmartins/church-members-api/internal/modules/report"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GenerateReport mocks base method.
func (m *MockService) GenerateReport(ctx context.Context, arg1 reportType.Type) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateReport", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateReport indicates an expected call of GenerateReport.
func (mr *MockServiceMockRecorder) GenerateReport(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateReport", reflect.TypeOf((*MockService)(nil).GenerateReport), ctx, arg1)
}

// GetReport mocks base method.
func (m *MockService) GetReport(ctx context.Context, name reportType.Type) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReport", ctx, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReport indicates an expected call of GetReport.
func (mr *MockServiceMockRecorder) GetReport(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReport", reflect.TypeOf((*MockService)(nil).GetReport), ctx, name)
}

// ListReports mocks base method.
func (m *MockService) ListReports(ctx context.Context) []report.Report {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReports", ctx)
	ret0, _ := ret[0].([]report.Report)
	return ret0
}

// ListReports indicates an expected call of ListReports.
func (mr *MockServiceMockRecorder) ListReports(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReports", reflect.TypeOf((*MockService)(nil).ListReports), ctx)
}
