// Code generated by MockGen. DO NOT EDIT.
// Source: ./notification.go

// Package mock_notification is a generated GoMock package.
package mock_notification

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// NotifyMobile mocks base method.
func (m *MockService) NotifyMobile(text, phone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyMobile", text, phone)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyMobile indicates an expected call of NotifyMobile.
func (mr *MockServiceMockRecorder) NotifyMobile(text, phone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyMobile", reflect.TypeOf((*MockService)(nil).NotifyMobile), text, phone)
}

// NotifyTopic mocks base method.
func (m *MockService) NotifyTopic(text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyTopic", text)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyTopic indicates an expected call of NotifyTopic.
func (mr *MockServiceMockRecorder) NotifyTopic(text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyTopic", reflect.TypeOf((*MockService)(nil).NotifyTopic), text)
}
