name: Go

on:
  push:
    branches: [ master ]
    paths:
      - "bundles/**"
      - "fonts/**"
      - "**.go"
  pull_request:
    branches: [ master ]
    paths:
      - "bundles/**"
      - "fonts/**"
      - "**.go"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: Test
        run: SCOPE=test go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      
      - name: Coverage
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
