name: Go

on:
  push:
    branches: [ master ]
    paths:
      - "resources/**"
      - "**.go"
  pull_request:
    branches: [ master ]
    paths:
      - "resources/**"
      - "**.go"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        run: SCOPE=test go test ./... -race -coverprofile=coverage.txt -covermode=atomic

      - name: Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
